### PR TITLE
Fix #130 - Use user-provided interval to refresh GTFS-rt feed

### LINKED ISSUE #130: Interval entered into UI doesn't control GTFS-rt feed refresh rate
**Summary:** 

In seems like the interval that you enter into the Welcome page when setting the GTFS-rt feed isn't actually being used to control how often we're fetching the GTFS-rt feed.

We have two sets of intervals which I assumed were both set by the input into the Welcome page:
1. The interval at which the web client refreshes it's view from the GTFS-rt validator server
1. The interval at which the server refreshes the GTFS-rt feed that the client wants to monitor

However, after some testing, it seems like the interval entered into the website is only controlling 1) above - it's not actually controlling how often we're fetching the GTFS-rt feed.

The interval input into the page should control both - and, to ensure that the client is always fresh and doesn't drift out of sync by a cycle with the GTFS-rt validator server, the web client interval should probably be half the interval used to fetch the GTFS-rt feed.

So, if I enter 10 seconds into the web form, it should:
* Set the web client refresh interval to 5 seconds
* Set the GTFS-rt validator fetch interval for the GTFS-rt feed to 10 seconds

**Steps to reproduce:** 

1. Set up a feed and enter 30 seconds for the monitoring interval

**Expected behavior:** 

1. The GTFS-rt validator should fetch the GTFS-rt feed every 30 seconds, and I should see a relatively fresh version of this in the client UI (based on my above design, the client interval for updating from the GTFS-rt validator server should be 15 seconds).

**Observed behavior:** 

1. The web client updates it's view of the data every 30 seconds, but the GTFS-rt validator server still fetches the GTFS-rt feed every 10 seconds.  If you look at the "Total HTTP Request" count, every time the web client updates it jumps by 3, because 3 HTTP requests have been made since the last time the web client updated it's view of the data.

**Platform:** 

Windows 7 Enterprise w/ jdk1.8.0_73 and Chrome v57.0.2987.133 (64-bit)

@mohangandhiGH Could you please take a look at this?

### PR DESCRIPTION
**Pull request by mohangandhiGH**
**Summary:**

Fixes #130. 

**Expected behavior:** 

The update interval of server is set to user entered interval in welcome page.
Update interval of client is set to half the update interval of server refresh rate.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `mvn test` to make sure you didn't break anything
- [x] Format the title like "Fix #issue - short description of fix and changes"
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by mohangandhiGH** [comment]
@barbeau Please see the actual commit [here](https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/132/commits/b046ce18da639894888f7277e06f9a844ba107ae).

**Comment by barbeau** [comment]
This looks good!  Although there are now conflicts after merging https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/129.  Let's get https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/129 merged first, and then you can rebase this on master and we can merge this as well.

**Comment by mohangandhiGH** [comment]
@barbeau Re-based this PR on master branch and force pushed the changes. Merging this PR :)

**Comment by barbeau** [comment]
Thanks!

**Pull request merged**
