### PR TITLE
Fix #68 - Add batch processing mode

### LINKED ISSUE #68: Ability to batch process local feed archive
I have a utility that polls a GTFS-RT feed and archives to S3 so later they can be downloaded for analysis. For example, here's what the structure looks like:

```
% find TripUpdates -type f | sort | head -n10
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-57-20Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-57-35Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-57-51Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-58-06Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-58-21Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-58-36Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-58-51Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-59-06Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-59-21Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-59-36Z.pb
```

The tool names the path and files based on the feed header timestamp.

It would be nice if I could run the validator against all these as if it had polled a single URL and received them in succession.

### PR DESCRIPTION
**Pull request by barbeau**
~~***Please don't merge***~~

~~This is a work-in progress.~~

Below is current summary of work in this branch:

* Add `BatchProcessor` for batch processing of archived GTFS-realtime files
* Add command-line batch processing mode
* Add utility method tests

TODO:
- [x] Add unit tests for output of results (JSON files)
- [x] Fix failure on Travis (see https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/279#issuecomment-329317169)

Here's an example of a command to batch process a set of GTFS-realtime files:

`java -jar target/gtfs-rt-validator-1.0.0-SNAPSHOT.jar -batch yes -gtfs "D:\HART\google_transit.zip" -gtfsrealtimepath "D:\HART\gtfs-rt" -sort date`

 Parameters:

 * `-batch` - Must be provided for the validator to start in batch processing mode.  If this parameter isn't provided, the server will start in the normal mode.
 * `-gtfs` - The path and file name of the GTFS zip file.  GTFS zip file must cover the time period for the GTFS-rt archived files.  You can combine GTFS zip files if needed using the [Google transitfeed tool's](https://github.com/google/transitfeed/wiki/Merge).
 * `-gtfsrealtimepath` - The path to the folder that contains the individual GTFS-realtime protocol buffer files
 * `-sort` *(Optional)* - `date` if the GTFS-realtime files should be processed chronologically by the "last modified" date of the file (default), or `name` if the files should be ordered by the name of the file. If you use the name of the file to order the files, then the validator will try to parse the date/time from each individual file name and use that date/time as the "current" time.  Date/times in file names must be in the [ISO_DATE_TIME](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_DATE_TIME) format and must be the last 20 characters prior to the file extension - for example, `TripUpdates-2017-02-18T20-00-08Z.pb`.  If a date/time can't be parsed from the file name, then the last modified date is used as the "current" time. GTFS-realtime file order is important for rules such as E012, E018, and W007, which compare the previous feed iteration against the current one.
* `-plaintext` *(Optional)* - If this argument is supplied, the validator will output a plain text version of each of the protocol buffer files with the provided file extension.  For example, if the protocol buffer file has the name `trip-update.pb`, and the text `-plaintext txt` is provided as the argument, then the plain text version of this file will be `trip-update.pb.txt`.

 After execution finishes, the results for each GTFS-realtime protocol buffer file will be output in JSON format with the same file name, but with "results.json" appended to the end.  For example, if one GTFS-realtime procotol buffer file name was `TripUpdates-2017-02-18T20-00-08Z.pb`, the validation results for that file will be output as `TripUpdates-2017-02-18T20-00-08Z.pb.results.json`. 
 
 It will look something like:
 
 ~~~
 [ {
   "errorMessage" : {
     "messageId" : 0,
     "gtfsRtFeedIterationModel" : null,
     "validationRule" : {
       "errorId" : "W001",
       "severity" : "WARNING",
       "title" : "timestamp not populated",
       "errorDescription" : "Timestamps should be populated for all elements",
       "occurrenceSuffix" : "does not have a timestamp"
     },
     "errorDetails" : null
   },
   "occurrenceList" : [ {
     "occurrenceId" : 0,
     "messageLogModel" : null,
     "prefix" : "trip_id 277716"
   }, {
     "occurrenceId" : 0,
     "messageLogModel" : null,
     "prefix" : "trip_id 277767"
   }, {
     "occurrenceId" : 0,
     "messageLogModel" : null,
     "prefix" : "trip_id 277768"
   }, 
   ...
~~~

In the above example, three `trip_updates` have been validated, and each was missing a timestamp (warning `W001`).  To put together the full message for each occurrence of the warning or error, you add the occurrence `prefix` to the validationRule `occurrenceSuffix`.

For example, in log format the above would look like:
* `trip_id 277716 does not have a timestamp`
* `trip_id 277767 does not have a timestamp`
* `trip_id 277768 does not have a timestamp`

### CODE REVIEW

**Comment by barbeau** [comment]
@Suryakandukoori Could you please give this a look and try it out and see if it works as you would expect it to?  See the main PR description for instructions and current output.

**Comment by barbeau** [comment]
Hmmm...I'm still seeing a failed build on Travis (https://travis-ci.org/CUTR-at-USF/gtfs-realtime-validator/builds/275242935), it says:

~~~
[INFO] Running edu.usf.cutr.gtfsrtvalidator.test.UtilTest
[ERROR] Tests run: 28, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.002 s <<< FAILURE! - in edu.usf.cutr.gtfsrtvalidator.test.UtilTest
[ERROR] testSortDate(edu.usf.cutr.gtfsrtvalidator.test.UtilTest)  Time elapsed: 0.001 s  <<< FAILURE!
junit.framework.AssertionFailedError
	at edu.usf.cutr.gtfsrtvalidator.test.UtilTest.testSortDate(UtilTest.java:722)
~~~

It's related to sorting the unit test resources files by file "date modified".  This passes locally on my machine (Windows) but fails on Travis (Linux), so it seems to be a cross-platform problem.  I originally was using "date created" but that seemed to return bogus values (Java values didn't match Windows Explorer values), which is why I used "date modified" instead (these values seemed more reasonable).  However, it appears that "date modified" has issues too.  Need to investigate more...

**Comment by danp** [comment]
Could be due to git not tracking timestamps on files? So when travis clones everything is created/modified/etc now. Having travis run `ls -la` at some point might help show what's up.

**Comment by barbeau** [comment]
@danp yeah, you're probably right. The unit tests for sorting files based on time should probably use temporarily created files within the test instead of actual files in the resources path. I'll check it out.

**Comment by barbeau** [comment]
@danp is correct, Git doesn't retain any file timestamp metadata, so that's why the tests failed with files bundled with the repo.

It looks me a few more tries to get this to work with temp files created at runtime within the unit test, though.  Interestingly, it looks like Windows provides a more granular timestamp on files than Linux, or at least the flavor of Linux that Travis runs.

Here's what I get on my Windows machine when printing out file names and last modified times:

~~~
[main] ERROR edu.usf.cutr.gtfsrtvalidator.test.UtilTest - tempFileOldest6977704004362107221.tmp 2017-09-19T01:16:18.803397Z
[main] ERROR edu.usf.cutr.gtfsrtvalidator.test.UtilTest - tempFileMiddle8629780685616714002.tmp 2017-09-19T01:16:19.307237Z
[main] ERROR edu.usf.cutr.gtfsrtvalidator.test.UtilTest - tempFileNewest3364893684128403964.tmp 2017-09-19T01:16:19.809092Z
~~~

Here's Travis:
~~~
[main] ERROR edu.usf.cutr.gtfsrtvalidator.test.UtilTest - tempFileOldest1013974040596222827.tmp 2017-09-19T01:01:25Z
[main] ERROR edu.usf.cutr.gtfsrtvalidator.test.UtilTest - tempFileMiddle8052286401962513362.tmp 2017-09-19T01:01:26Z
[main] ERROR edu.usf.cutr.gtfsrtvalidator.test.UtilTest - tempFileNewest7290542805729847594.tmp 2017-09-19T01:01:26Z
~~~

Adding a 1.5 second `Thread.sleep()` fixes this by forcing the temp files to be created at different seconds.

**Pull request merged**
