### PR TITLE
Fix #139 - Add iteration details page to show problems found in that iteration

### LINKED ISSUE #139: Add iteration details page to show problems found in that iteration
**Summary:** 

Currently, when clicking on the Iteration number in the validation tool, we show a popup window for the plain text GTFS-rt for that iteration:

image

This is useful, but I'd like to expand it into it's own page that provides a summary of all errors and warnings for that iteration - this is where tracking down exact problems will be very useful.

So, the new design would be:
1. Click on iteration ID
1. Open new page in a new tab that shows all the errors and warnings for that iteration

Here's a mockup of what this new page should look something like:

image

(ignore the specific color choices here for background, etc - the defaults for the normal UI we're using should be fine)

On the left, we keep the same UI for showing the plain text protobuf from the feed, including the copy-to-clipboard icon.  On the right, we show a number of cards that detail the various errors and warnings found in that feed iteration

Feature details:
* We should be able to view multiple iteration pages in multiple browser tabs at a time.  Sometimes we will need to cross reference more than one iteration at a time.
* Errors should always appear above warnings, as they are more important.  We can sort by rule name order (E001, E002, E003, ... W001, W002, W003...).
* Left and right panes should scroll independently - the user should be able to scroll to a particular location in the plain text feed, and scroll to a related rule on the right.  This will help uses track down problems related to specific trip IDs, etc.
* If there are more than 3 occurrences for a rule, we limit the number of records shown to 3 and add a "...and 50 more" in a new row at the bottom of that table.  Clicking on "...and 50 more" would open a new window showing all occurences for this iteration and rule (see mockup below)
* We should add a download button to download a CSV file of all problems found in this iteration of the feed, as well as one to download just specific rules (see mockup below).
* User should be able to easily search for text within the protobuf plain text window.  For example, if I see the error "trip_id 6246 is not in the GTFS data" in the right column, I should be able to copy "6246" to my clipboard, do a Ctrl-F, and easily search for that text in the plain text version of the feed in the left column.

I still need to work on the field used to populate the "Summary" field in the tables - I'll comment when I have an example for one of the rules that we can use.

@mohangandhiGH I think this is biggest priority right now after https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/120, so let's focus on this next.  The CSV download implementation doesn't necessarily need to be included in the PR for this if it adds a lot of work - I'd really like to get the iteration details UI in place first.

Clicking on "...and 50 more" mockup:

image

Clicking on "Download" link mockup - for all rules and a single rule:

image

image

**Steps to reproduce:** 

1. Monitor a feed
1. Click on Iteration ID

**Expected behavior:** 

Show me more details about the problems found in that feed iteration, as well as a plain text version of the feed.

**Observed behavior:** 

A plain text version of the feed is shown, but without any details about occurrences in that feed.

**Platform:** 

N/A

### PR DESCRIPTION
**Pull request by mohangandhiGH**
**Summary:**

When an iteration id link is clicked, it displays all the iteration errors/warnings and feed message text in new window. 
Fixes #139 .

**Expected behavior:** 

Here are the screenshots of iteration details.

image

image

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `mvn test` to make sure you didn't break anything
- [x] Format the title like "Fix #issue - short description of fix and changes"
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by mohangandhiGH** [comment]
@barbeau This PR doesn't actually contain the changes to download the errors/warnings.
 Could you please take a look into it and review the changes.

**Comment by mohangandhiGH** [comment]
I think we can always have a better look to the UI after everything is in place.

**Comment by barbeau** [comment]
@mohangandhiGH Sure, this PR doesn't need the download link.  We can do that in another PR.  I'm looking at this now - so far it looks great! :)

**Comment by barbeau** [comment]
Something else to discuss - creating a URL specific to this Iteration that can be shared with another user.  For example:
http://localhost:8080/iteration/378594?sessionIteration=123

In this example the primary key in the database would be 378594, and the iteration ID to show at the top of the page would be 123.

**Comment by barbeau** [comment]
Per our discussion today, we're going to implement the shareable URL as part of a different issue/pull request - I just opened https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/177 for this.

**Comment by barbeau** [comment]
Also per our discussion today, we're going to push back the download buttons into a separate issue so we can merge this PR faster.  Here's the new download buttons issue - https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/178.

**Comment by barbeau** [comment]
Per comments at https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/182#issuecomment-298256822, closing this in favor of https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/182.

**Pull request closed without merging**
