### PR TITLE
Fix #100 - Show plain text version of feed message when clicking on Log Iteration number

### LINKED ISSUE #100: Show plain text version of feed message when clicking on Log Iteration number
**Summary:** 

For each record in the `Log`, we show an `Iteration` number in blue text.  When clicking on this number, it should open up a window showing the plain text version of the protocol buffer that was saved for that iteration (i.e., to view the exact protocol buffer data that generated that particular warning/error in the database).

image

Because we're already storing the binary protocol buffer message for each record in the `Log`, we should just be able to convert this to plain text and show it in a popup window that's scrollable (the text could be quite large).  We should also be able to copy text from the window to the clipboard (e.g., to copy an ID or timestamp from the feed) by clicking and dragging the cursor within the window and using keyboard shortcut (e.g., Ctrl+C), and we should include a "copy-to-clipboard" icon to easily copy the entire protocol buffer text to clipboard (maybe using https://clipboardjs.com/? Or whatever works).  The above mockup has one in the lower-right corner, but I'm open to alternate designs if they make sense.

**Steps to reproduce:** 

Start the validator with feeds

**Expected behavior:** 

Let me click on the `Iteration` number to see the protocol buffer text for the feed iteration that generated that particular error or warning. 

**Observed behavior:** 

Nothing happens when I click on the `Iteration` number.

### PR DESCRIPTION
**Pull request by mohangandhiGH**
**Summary:**

Fixes #100. 

**Expected behavior:** 

When we click on Log iteration number, plain text version of feed message is shown as below. 

image

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `mvn test` to make sure you didn't break anything
- [x] Format the title like "Fix #issue - short description of fix and changes"
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by mohangandhiGH** [comment]
@barbeau I have made changes to 
*  Title of dialog box
*  Position of copy button

But, to my knowledge, I did not find any way to `resize the window with a scrollbar`.

**Comment by barbeau** [comment]
@mohangandhiGH Sorry - could you please rebase this on master, and force push to this PR?  There were conflicts after merging https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/118, and I tried to resolve them view the Github UI, but that resulted in a merge commit with master, and it looks like I broke monitoring in the process :(.  If you could push new version of changes that would be great.

**Comment by barbeau** [comment]
Oh, and the changes look good here!  It's ready to merge after a rebase.

**Comment by mohangandhiGH** [comment]
@barbeau I rebased this PR on master and force pushed the changes. Now we can merge this PR

**Comment by mohangandhiGH** [comment]
Merged this PR :)

**Comment by barbeau** [comment]
Thanks!

**Pull request merged**
