### PR TITLE
Fix #80 - Allow showing/hiding Gtfs-rt errors in Log

### LINKED ISSUE #80: Allow showing/hiding GTFS-rt errors in log view
**Summary:** 

Based on our most recent mockups in https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/77#issuecomment-285805813, we're going to be displaying a summary of the feed with a count of all errors/warnings above a short view of the log, which for now is the most recent 10 records.  After that PR, the UI will look something like:

image

We still need to figure out detailed controls for the log portion, but for now I'd like to implement a simple ability show/hide specific error/warning types.  For example, if we know that none of the VehiclePosition or TripUpdate entities have timestamps, and there isn't anything we can do about that from the underlying source data, I want to hide these errors from the detailed log so I can look at other errors/warnings I care about.

Here's a possible mockup of how this could look - a simple switch next to each error/warning in the summary view.  When clicking on "Show", it shows all log entries for that error/warning.  When clicking on "Hide", it hides all log entries for that error/warning.  We'll probably want to persist the values of these switches for specific feeds as user preferences, so the user doesn't have to flip these for each execution of the app.  For example, if I want to hide all "Timestamp not populated" warnings, I can click on "Hide" for this warning once, and for all executions going forward it will stay hidden.

image

**Steps to reproduce:** 

Run the validator on a GTFS-rt feed

**Expected behavior:** 

Give me a way to filter the log to hide errors/warnings I don't care about

**Observed behavior:** 

We don't have any way to filter the detailed log

**Platform:** 

N/A

### PR DESCRIPTION
**Pull request by mohangandhiGH**
**Summary:**

This pull request adds the functionality to show/hide errors in log. Fixes #80.

**Expected behavior:** 

Below are the error summary and error log view

image

So, if we toggle to hide an error, for example as shown in the below image error `w001` is hidden, then it should not diaplay the hiddden errors in log.

image

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `mvn test` to make sure you didn't break anything
- [x] Format the title like "Fix #issue - short description of fix and changes"
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by barbeau** [comment]
Thanks @mohangandhiGH!  I tried to run this without deleting my local database files after executing https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/77 and with the HART GTFS and GTFS-rt, and I got the below error when trying to load the feeds:

~~~
[main] INFO org.eclipse.jetty.server.Server - Started @9373ms
[main] INFO edu.usf.cutr.gtfsrtvalidator.Main - Go to http://localhost:8080 in your browser
[qtp32393008-29] INFO edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeed - Downloading GTFS data from http://gohart.org/google/google_transit.zip...
2017-03-26T14:44:22.763-0400  WARN  SQL Error: -5501, SQLState: 42501
2017-03-26T14:44:22.764-0400  ERROR  user lacks privilege or object not found: GTFSFEEDMO0_.AGENCY in statement [select gtfsfeedmo0_.feedID as feedID1_1_, gtfsfeedmo0_.agency as agency2_1_, gtfsfeedmo0_.fileChecksum as fileChec3_1_, gtfsfeedmo0_.errorCount as errorCou4_1_, gtfsfeedmo0_.fileLocation as fileLoca5_1_, gtfsfeedmo0_.feedUrl as feedUrl6_1_, gtfsfeedmo0_.downloadTimestamp as download7_1_ from GtfsFeed gtfsfeedmo0_ where gtfsfeedmo0_.feedUrl='http://gohart.org/google/google_transit.zip']
[qtp32393008-29] WARN org.eclipse.jetty.servlet.ServletHandler - 
javax.servlet.ServletException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:423)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:147)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:155)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1407)
	at org.hibernate.query.internal.AbstractProducedQuery.uniqueResult(AbstractProducedQuery.java:1438)
	at edu.usf.cutr.gtfsrtvalidator.api.resource.GtfsFeed.postGtfsFeed(GtfsFeed.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403)
	... 17 more
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:182)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1940)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1909)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1887)
	at org.hibernate.loader.Loader.doQuery(Loader.java:932)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:349)
	at org.hibernate.loader.Loader.doList(Loader.java:2615)
	at org.hibernate.loader.Loader.doList(Loader.java:2598)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2430)
	at org.hibernate.loader.Loader.list(Loader.java:2425)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:502)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1458)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1426)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1398)
	... 41 more
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: GTFSFEEDMO0_.AGENCY in statement [select gtfsfeedmo0_.feedID as feedID1_1_, gtfsfeedmo0_.agency as agency2_1_, gtfsfeedmo0_.fileChecksum as fileChec3_1_, gtfsfeedmo0_.errorCount as errorCou4_1_, gtfsfeedmo0_.fileLocation as fileLoca5_1_, gtfsfeedmo0_.feedUrl as feedUrl6_1_, gtfsfeedmo0_.downloadTimestamp as download7_1_ from GtfsFeed gtfsfeedmo0_ where gtfsfeedmo0_.feedUrl='http://gohart.org/google/google_transit.zip']
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172)
	... 57 more
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: GTFSFEEDMO0_.AGENCY
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.ExpressionColumn.checkColumnsResolved(Unknown Source)
	at org.hsqldb.QueryExpression.resolve(Unknown Source)
	at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source)
	at org.hsqldb.Session.compileStatement(Unknown Source)
	at org.hsqldb.StatementManager.compile(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 61 more
~~~

The GTFS download bar was red.

If I delete the local database and start from scratch then it seems to work fine.

**Comment by mohangandhiGH** [comment]
@barbeau In the latest changes of PR #77, an extra field `agency` was added in `GtfsFeed` table. I think you have not cleaned your database after that PR is merged. Could you please clean the database and run the application again.

**Comment by barbeau** [comment]
If I delete the database files it runs fine.  I thought the database should update itself, though, and there shouldn't be problems when making more changes to the database? We can't expect users to delete their data each time we add fields.

**Comment by mohangandhiGH** [comment]
@barbeau Currently, we are still using `createTables.sql` file to create our initial database schema. We can open an issue to stop using `createTables.sql` file to create schema and use hibernate persistence classes to do that.

**Comment by barbeau** [comment]
Yes, great, let's do that. For this PR, then, you can fix the UI issue and it should be ready to merge.

**Comment by mohangandhiGH** [comment]
Okay Sean.

**Pull request merged**
