### PR TITLE
Fix #352 close input streams on protobuf file reads.

### LINKED ISSUE #352: Protobuf files being read by BatchProcessor are never closed.
**Summary:** 

Protobuf files being read by BatchProcessor are never closed.

**Steps to reproduce:** 

Run batch processor, while it is operating any .protobuf files that it has created cannot be deleted from the filesystem or otherwise edited.

**Expected behavior:** 

Expect the application to close the input stream after reading protobuf files.

**Observed behavior:** 

Application holds a lock on protobuf files it has read while the application is running.

**Platform:** 

Java 8, Windows.

### PR DESCRIPTION
**Pull request by KyleGancarz**
**Summary:**

Fix #352 Protobuf files being read by the batch processor never get closed.

**Expected behavior:** 

Protobuf files being read by the batch processor will be properly closed. My apologies @barbeau, but I jumped the gun on the earlier commit for this issue. ViewFeedMessageModel's input stream was not being closed and needed to be addressed.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x ] Run the unit tests with `mvn test` to make sure you didn't break anything
- [x ] Format the title like "Fix #<issue_number> - <short description of fix and changes>" (for example - "Fix #1111 - Check for null value before using field")
- [x ] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by KyleGancarz** [comment]
false alarm.

**Comment by barbeau** [comment]
@KyleGancarz ok - so the original fix seems to have resolved the problem?

**Comment by KyleGancarz** [comment]
Yes, the original fix did the trick.

**Comment by barbeau** [comment]
Great, thanks!

**Pull request closed without merging**
