### PR TITLE
Fix #22 - Integrating laidig_validator into gtfs-realtime-validator to validate GTFS feed

### LINKED ISSUE #22: Integrating laidig-validator into gtfs-realtime-validator
For validating the GTFS feed in gtfs-realtime-validator, we want to use [laidig-validator](https://github.com/laidig/gtfs-validator) which is usually very faster than [google validator](https://github.com/google/transitfeed). 
So, need to update pom.xml and  other files as needed, so that gtfs-realtime-validator project can depend on laidig-validator for validation of GTFS data.

### PR DESCRIPTION
**Pull request by mohangandhiGH**
This PR depends on laidig_validator jar version 0.1.1.  For now, this laidig_validator version is cloned locally and installed, for this PR to work. 

Also creates and stores MD5 hash for the input static GTFS feed, so that the same GTFS feed is not validated again.

Fix #22

### CODE REVIEW

**Comment by barbeau** [comment]
@mohangandhiGH To allow Travis to build, can you please add a reference to the camsys repository in the pom.xml of this project?

See this file for address of that repo:
https://github.com/conveyal/gtfs-validator/blob/master/pom.xml#L54

Then you'll need to add the following as a dependency in the pom.xml:

~~~
    <groupId>com.conveyal</groupId>
    <artifactId>gtfs-validator</artifactId>
    <version>0.0.1-SNAPSHOT</version>
~~~

This will use the artifacts of the conveyal/gtfs-validator project by default.  If you install the laidig/gtfs-validator locally via `mvn install` it will override the conveyal project.

**Comment by mohangandhiGH** [comment]
@barbeau camsys repository does not have com.conveyal/gtfs-validator/0.0.1-SNAPSHOT jar file. But it has jar files for separate modules gtfs-validator-json/0.0.1-SNAPSHOT and gtfs-validation-lib/0.0.1-SNAPSHOT.
But, for module gtfs-validation-lib, we need 0.1.3 version jar which is not there in camsys repository.

**Comment by barbeau** [comment]
Ah, right, and you'd already have that in our pom.xml.  You're right, looks like laidig bumped the version ahead of conveyal gtfs-validator.  I just created this PR which will try to clone and `mvn install` his repo on Travis:
https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/28

Let's see if that works...

**Comment by barbeau** [comment]
Alright, looks like that is working, so we can just use that for now.  I'll squash and merge #28.

**Comment by barbeau** [comment]
@mohangandhiGH Could you also please update the README steps with the `mvn install` for the laidig gtfs-validator?

**Comment by mohangandhiGH** [comment]
@barbeau Yah Sean, I will do that

**Comment by laidig** [comment]
maybe try https://jitpack.io/#maven ?

**Comment by barbeau** [comment]
@laidig Interesting!  Thanks for sharing, hadn't seen that.  We'll take a look.

**Pull request merged**
