### PR TITLE
Logging dependency missed in gtfs-realtime-validator-webapp module

### PR DESCRIPTION
**Pull request by Suryakandukoori**
**Summary:**

Logging dependency now added to gtfs-realtime-validator-webapp module pom.xml

**Expected behavior:** 

No errors in the build

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Run the unit tests with `mvn test` to make sure you didn't break anything
- [X] Format the title like "Fix #issue - short description of fix and changes"
- [X] Linked all relevant issues
- [X] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by barbeau** [comment]
@Suryakandukoori Interesting - what error are you seeing?

I'm able to run the project fine on my my local machine without it, and it builds ok on Travis too.

Did you do a `mvn clean` or clean via IntelliJ and reimport the Maven project before running the project?

The Maven project structure changed which might cause problems if you don't clean first.

**Comment by Suryakandukoori** [comment]
@barbeau I saw an error while importing the class org.slf4j.LoggerFactory. The entire workspace had no other problems, the moment I added this dependency, the import error was fixed, hence I raised this pull request.
Now, I did a 'mvn clean install' which fixed the problem. This pull request is no longer required.

**Comment by barbeau** [comment]
Ok, thanks for checking!  Yes, IntelliJ freaked out a bit the first time I pulled in the new changes to the master branch due to the change in project config and addition of submodules, but it seems to settle out.

**Comment by barbeau** [comment]
Also, I did a re-org of the README docs - you might want to take a look at the root README again just to see what's changed.

**Pull request closed without merging**
