### PR TITLE
Fix #23 - Integrating gtfs-validator webapp into gtfs-realtime-validator

### LINKED ISSUE #23: Integrate gtfs-validator-webapp UI for static GTFS validation results
laidig-webapp provides a way to view the static GTFS validation report via a web UI. It's better if we integrate this feature in gtfs-realtime-validator, so that a user can have better view of the static validation report before running the real-time validation.

### PR DESCRIPTION
**Pull request by mohangandhiGH**
Fix #23

### CODE REVIEW

**Comment by barbeau** [comment]
As we discussed in today's meeting, we're going to hold off on merging this to see if we can find a solution that refers to the gtfs-validator-webapp as a dependency instead of copying in the files in this PR.

**Comment by barbeau** [comment]
This should fix https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/51 if we're able to reference the laidig gtfs-validator fork artifacts.

**Comment by barbeau** [comment]
@mohangandhiGH could you please rebase this commit on the master branch? I'd like to make sure Travis passes.

**Comment by mohangandhiGH** [comment]
@barbeau after this PR https://github.com/conveyal/gtfs-validator/pull/24, there are no compile errors and everything is fine, but when I tried to **run** the web server to see the validation report, I encountered with this issue https://github.com/conveyal/gtfs-validator/issues/25 and I commited changes for this issue in PR https://github.com/conveyal/gtfs-validator/pull/26. As soon as PR  https://github.com/conveyal/gtfs-validator/pull/26 is merged and included in latest version, hopefully I can make sure that Travis build passes.

**Comment by barbeau** [comment]
@mohangandhiGH Ok, thanks for the explanation!

**Comment by barbeau** [comment]
Also, let's wait to merge this until the conveyal/gtfs-validator is updated.

**Comment by mohangandhiGH** [comment]
@barbeau If you got some time, could you please pull this PR changes and check whether the build is passed or not? Please, try to run the build via Command Prompt in **administrators mode**.

And we can discuss more about this in tomorrows meeting.

**Comment by barbeau** [comment]
It seems to build fine with `mvn clean install -U` even without Admin rights from git bash (from within IntelliJ), although if I run in IntelliJ I get the below screen when clicking on "GTFS Validation Report" button - I'm assuming this is because it's not running as Admin?:

image

**Comment by barbeau** [comment]
I guess you probably saw that the [Travis build](https://travis-ci.org/CUTR-at-USF/gtfs-realtime-validator/builds/207115049) is failing with the error:

~~~
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2:exec (component-build) on project gtfs-rt-validator: Command execution failed. Cannot run program "/home/travis/build/CUTR-at-USF/gtfs-realtime-validator/target/node/component-build.cmd" (in directory "/home/travis/build/CUTR-at-USF/gtfs-realtime-validator/target/classes/webroot/gtfs-rt-validator-webapp/gtfs-validator-master/gtfs-validator-webapp"): error=2, No such file or directory -> [Help 1]
[ERROR] 
~~~

**Comment by mohangandhiGH** [comment]
> It seems to build fine with mvn clean install -U even without Admin rights from git bash (from within IntelliJ)

Although it seems to build fine, you might will see an error if you look into the build log in git bash.
Here is the error part you might see. This error is due to failing to create `symlink` due to lack of admistartor previliges.

 ~~~ 
error?[m : ?[90mError: EPERM: operation not permitted, symlink 'C:\Users\mohan\Desktop\GTFS-RT\gtfs-realtime-validator\target\classes\webroot\gtfs-rt-validator-webapp\g
tfs-validator-master\gtfs-validator-webapp\components\components\bootstrap\3.3.7\fonts\glyphicons-halflings-regular.eot' -> 'C:\Users\mohan\Desktop\GTFS-RT\gtfs-realtime-validator\
target\classes\webroot\gtfs-rt-validator-webapp\gtfs-validator-master\gtfs-validator-webapp\build\components\bootstrap\3.3.7\fonts\glyphicons-halflings-regular.eot'
~~~

**Comment by mohangandhiGH** [comment]
>I guess you probably saw that the Travis build is failing with the error:

yah, I saw the error in travis. But I don't understand why it's unable to execute the component-build command 
~~~
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2:exec (component-build) on project gtfs-rt-validator: Command execution failed. Cannot run program "/home/travis/build/CUTR-at-USF/gtfs-realtime-validator/target/node/component-build.cmd" (in directory "/home/travis/build/CUTR-at-USF/gtfs-realtime-validator/target/classes/webroot/gtfs-rt-validator-webapp/gtfs-validator-master/gtfs-validator-webapp"): error=2, No such file or directory -> [Help 1]
~~~
  Everything is building fine locally.

**Comment by barbeau** [comment]
https://github.com/conveyal/gtfs-validator/pull/36 is now merged, so this PR can be rebase on master to prep for review.

**Comment by barbeau** [comment]
Looks good, a few minor UI changes:

1. On "Checking Feed..." screen, let's remove the "GTFS Validation" and "Continue" buttons.  And, we'll change the dialog button on success to a green "Continue"
1. On "Monitoring Feed(s)" screen, let's change the "GTFS Validation Report" button to be a simple hyperlink instead, like "GTFS Validation Results: 1 error(s), 10 warning(s)", with the "errors and warnings" being hyperlinked to http://localhost:8080/gtfs-rt-validator-webapp/gtfs-validator-master/gtfs-validator-webapp/index.html?report=http://localhost:8080/google_transit_out.json.

So it would look something like:

image


1. Let's also move the GTFS Validation Report above the "Overview" section so the GTFS validation is at the top, and the GTFS-rt validation is everything below that.

**Comment by barbeau** [comment]
It looks like this issue in the gtfs-validator project is blocking us from seeing static validation results - https://github.com/conveyal/gtfs-validator/issues/17.

**Comment by mohangandhiGH** [comment]
@barbeau Pushed in the latest changes. Here are the modified screen shots.

If there is any error in loading feeds, for example, the following dialog appear for GTFS static feed load failure and after clicking `Ok` button, user can again go "Back" or "Retry"

image

After loading the feeds successfully, the following dialog appears with a message saying "GTFS feeds are loaded successfully. GTFS static data has been validated. Continue to start monitoring GTFS-Realtime feeds.

image

After clicking "Continue", it will take to the Monitoring feeds section and here is a screenshot of it.


image

**Comment by barbeau** [comment]
Thanks @mohangandhiGH, looks good!  I'll go ahead and merge this, and open a new issue for the problem mentioned in https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/30#issuecomment-292645731.

**Pull request merged**
