### PR TITLE
Fix #256 - Only validate the combinedFeedMessage in the CrossFeedDescriptorValidator

### LINKED ISSUE #256: Summary shows for wrong feed
**Summary:** 

When running the GTFS-RT Validator on both a service alerts feed and a vehicle positions one, the 
vehicle positions summary/error section is is displayed for both. When I click on an iteration, the feed messages are displayed properly but the error messages are still there.

**Platform:** 
Windows 7. Chrome/Firefox

**Error Summary**
errorsummary

**Iteration Summary for an Empty Service Alerts .PB file**
iteration

In both cases the compiled protobuf files are written as .txt because of server restrictions.

### PR DESCRIPTION
**Pull request by barbeau**
**Summary:**

When this tool was originally built, some of the first rules written were for cross-referencing errors between two feeds (i.e., rules W003 and E047 in what is now `CrossFeedDescriptorValidator`). So, for each iteration, `BackgroundTask` around line 167 grabbed all the GTFS-rt messages for all GTFS-rt feeds that are being monitored simultaneously for the same GTFS data from the database and this `combinedFeed` was passed into the rules to be validated.

The problem with this is just that - other rules implemented in the other validator classes such as `VehicleValidator` were running on ALL messages from ALL GTFS-rt feeds associated with the same GTFS data. As a result, everything works fine when only one GTFS-rt feed per GTFS was running, but errors mix across multiple feeds when multiple GTFS-rt feeds were being monitored for the same GTFS data.

This patch adds another method parameter to our `FeedEntityValidator` interface that all rules implement specifically for the `combinedFeedMessage`, and passes in only the `currentFeedMessage` for the `feedMessage` parameter. `CrossFeedDescriptorValidator` only validates the `combinedFeedMessage` (not the `feedMessage`, which will be a subset of the `combinedFeedMessage`), and all other rules ignore the `combinedFeedMessage` and validate the `feedMessage`.

@Suryakandukoori Can you please review and test, and merge if all looks ok?

**Expected behavior:** 

Tested using:
* http://www.psta.net/Latest/google_transit.zip
* http://ridepsta.net/gtfsrt/alerts
* http://ridepsta.net/gtfsrt/vehicles

Before this patch the vehicle feed errors showed up in the alerts feed Summary and Log (left), and after this patch the alerts feed doesn't show any errors from the vehicle feed (right):

image

- [X] Run the unit tests with `mvn test` to make sure you didn't break anything
- [X] Format the title like "Fix #issue - short description of fix and changes"
- [X] Linked all relevant issues
- [X] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by Suryakandukoori** [comment]
@barbeau 
working on it Sean

**Comment by Suryakandukoori** [comment]
@barbeau 
Could you share read permissions to your fork so that I could fetch your changes and test them locally on my system?

**Comment by barbeau** [comment]
This PR is actually from a branch on the main repo, so it should be publicly readable - try:

~~~
git fetch origin
git checkout -b mixed-messages origin/mixed-messages
git merge master
~~~

**Comment by barbeau** [comment]
Note that you'll need to change `origin` to whatever your local name for the main repo is - if I'm working on my fork I usually use `upstream`. You can see your remote names if you forgot with `git remote - v`

**Comment by Suryakandukoori** [comment]
@barbeau 
I assumed you were actually working on your forked repository. I took the changes thank you!

**Comment by Suryakandukoori** [comment]
I named the main repo as 'remote' :-)

**Comment by Suryakandukoori** [comment]
@barbeau 
Do you think we should add a wrapper class to all the arguments of 'validate' method of 'FeedEntityValidator' and name it as 'ValidatorInput'? Readability would improve as per my opinion. I will do it if required

**Comment by barbeau** [comment]
Yeah, that's a good idea. I think we started with two parameters and it's
blown up quite a bit since then.

Thanks for volunteering! :)

Could you open a new issue for this, and open separate PR after this PR is
merged? Otherwise there will be conflicts.

**Comment by barbeau** [comment]
Awesome, thanks!

**Pull request merged**
