### PR TITLE
Fix #214 - Properly separate data across simultaneous feeds

### LINKED ISSUE #214: Validation data is mixing across feeds
**Summary:** 

I first noticed this in https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/210#issuecomment-303919066.

If you leave the server running and switch between monitoring feeds, data from one feed seems to show up in the other results.

**Steps to reproduce:** 

1. Go to localhost, add HART TripUpdates feed, start monitoring feed, click on "Stop", close tab
1. While the server is still running (and the BackgroundTask is still running), open a new tab and go to localhost again, add MBTA feed, start monitoring feed, and click on "Stop"
1. While server is still running, add HART VehicleUpdates feed, start monitoring

**Expected behavior:** 

The tool should properly isolate sessions (i.e., you'd only see MBTA data/results when monitoring the MBTA feed, and HART data/results when monitoring the HART feed), and not mix data from two different feeds/agencies from the same browser.  The `BackgroundTask` would currently be expected to continuously run at this point, as we aren't stopping it at any place in the code - but we should still be able to isolate feed/sessions when showing data via web UI.

**Observed behavior:** 

It seems like it started mixing results, where it was giving me a `E028	Vehicle position outside agency coverage area` error for the MBTA feed using a vehicle position from HART's data.  If I went to the Iteration Details page the error showed up there with a vehicle_id that wasn't in the MBTA GTFS-rt plain text version of the protobuf in the left column.

**Platform:** 

Windows 7 Enterprise w/ jdk1.8.0_73 and Chrome Version 58.0.3029.110 (64-bit)

### LINKED ISSUE #215: Support multiple clients with simultaneous feed monitoring
**Summary:** 

This is a continuation of the issue https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/101, restarted here due to clutter in the old issue.

Currently, even though we have a client/server model (Javascript UI and Jetty server), I believe some areas of code still only supports a single user - the application has been tested mostly in a `localhost` configuration.  We need to audit the current code and change to support multiple clients in a traditional client/server configuration.

The intended design is to have one thread monitoring each GTFS-rt feed, and each client should have a view of the validation data generated by that thread, defined by the starting and ending time of their particular monitoring session.

Known related issues:

* Clicking on "Stop" button doesn't stop monitoring - https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/204
* ~~Validation data is mixing across feeds - https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/214~~ **EDIT** - Fixed via https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/234 (we believe - let's still double-check).
* We will also need to handle the case where one client wants to monitor the feed more often than another - the lowest interval value (i.e., most frequent interval request) should win
* We also need to handle the case where the user enters more than one GTFS-realtime feed (i.e., one Trip Updates and one Vehicle Positions) within the same monitoring session.  `W003` is an example of a warning that checks both feeds.

**Steps to reproduce:** 

1. Start the tool
1. Open multiple incognito browsers to http://localhost:8080 and monitor different feeds, as well as the same feed in more than one browser with a different start time

**Expected behavior:** 

The tool should properly separate sessions and feed validation data.  There should be a single thread fetching the GTFS-rt data and generating validation results for each feed being monitored, with each client having a view of that feed data based on their session start (and end) times.

**Observed behavior:** 

See the above known issues.  There may be other problems as well - we need to audit execution and make sure nothing else strange is happening.

**Platform:** 

Windows 7 Enterprise w/ jdk1.8.0_73 and Chrome Version 58.0.3029.110 (64-bit)

### PR DESCRIPTION
**Pull request by mohangandhiGH**
**Summary:**

Towards multiple clients with simultaneous feeds monitoring. ~~Fixes #215.~~ Fixes #214.

**Expected behavior:** 

 Multiple clients are monitored without mixing the errors/warnings.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `mvn test` to make sure you didn't break anything
- [x] Format the title like "Fix #issue - short description of fix and changes"
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by mohangandhiGH** [comment]
*  Earlier, there is a bug in forming the `combinedFeed` in `BackgroundTask.java`. If 2 feeds are being monitored, `combinedFeed` used to have the 2 feeds GTFS-realtime feeds. So, while validating 1st feed, it is actually also recording errors from the 2nd feed sent to each **validateEntity** method in the `combinedFeed` parameter and vice-versa. 

      Now made sure that the `combinedFeed` will have only GTFS-realtime feeds of currently monitoring feed. 

*  Also modified to separate the start time for each feed being monitored using "sessionStorage" of `sessionStartTime`.

I have tested and saw that the multiple feeds are monitored independently without mixing validation results. 

@barbeau @Suryakandukoori @kevinsafon Could you please also make sure that there is no mixing of data.

**Comment by barbeau** [comment]
Thanks @mohangandhiGH, this is great!  I'll try to review tomorrow morning.

BTW, though - I think this fixes https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/214, but not necessarily all the items under #215?  Please let me know if I'm wrong.

**Comment by mohangandhiGH** [comment]
>>BTW, though - I think this fixes #214, but not necessarily all the items under #215? Please let me know if I'm wrong.

Yes Sean, It fixes only #214.

**Comment by barbeau** [comment]
Ok, thanks.  I'm updating the PR title and description to show #214 then.

**Comment by barbeau** [comment]
Thanks @mohangandhiGH!  I've tested, and I don't see the mixing of data any more, so that's good!  I'm going to leave #215 open, as I'd still like @Suryakandukoori to go through the entire lifecycle with a fresh pair of eyes to make sure some of the other items under #215 work.  I believe this should take care of #214, though!

**Pull request merged**
