### PR TITLE
Fix #178 - Add download button to iteration details page

### LINKED ISSUE #178: Add download button to iteration details page
**Summary:** 

PR https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/171 is adding a nice new iteration details page that you see after clicking on the iteration number in the Log view.

We'd like to add download buttons in this view to allow:
1. Downloading all error occurrences for this iteration in a CSV file
1. Downloading occurrences for a specific error/warning code in a CSV file

This was originally discussed in https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/139, but we're moving it to a new issue so we can get PR https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/171 merged more quickly.

Here's a mockup of what this new page should look something like in general with the download buttons:

image

Mockup for clicking on "Download" link - for all rules and a single rule:

image

image

**Steps to reproduce:** 

1. Monitor a feed
1. Click on Iteration ID

**Expected behavior:** 

Give me an option to download the errors in CSV format

**Observed behavior:** 

There is no way to download error occurrences details.

### PR DESCRIPTION
**Pull request by mohangandhiGH**
**Summary:**

Fixes #178.

**Expected behavior:** 

Added download button to each of the error cards in iteration details page. When we click on download button, the table data is exported in 'csv' format.

Here is a sample screenshot:

image

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `mvn test` to make sure you didn't break anything
- [x] Format the title like "Fix #issue - short description of fix and changes"
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

### CODE REVIEW

**Comment by barbeau** [comment]
@mohangandhiGH This looks great!  Unfortunately, though, I couldn't seem to get it to work properly.

I checked out this branch and executed run in IntelliJ, and used MBTA feeds:
* http://developer.mbta.com/lib/GTRTFS/Alerts/TripUpdates.pb
* http://www.mbta.com/uploadedfiles/MBTA_GTFS.zip

I could see the download button but clicking on it didn't seem to have any effect.  I was using Windows 7 Enterprise w/ jdk1.8.0_73 and Chrome Version 58.0.3029.110 (64-bit).

**Comment by mohangandhiGH** [comment]
@barbeau Ahhh, sometimes there might be problem updating the script pages in browser. Expecting that might be the issue,
Could you please go to the iterations details page and right click on it to open `inspect element` link. Once the `inspect element` window is opened, go to the `Network` tab and **uncheck** and **check** the `Disable cache` checkbox. Then refresh the iterations page.

Please let me know whether you are able to download after doing this.

**Comment by barbeau** [comment]
Ok, thanks, I'll try that - might be early tomorrow.

**Comment by mohangandhiGH** [comment]
@barbeau Updated the requested changes Sean.

**Comment by barbeau** [comment]
@mohangandhiGH Thanks, this is awesome!

**Pull request merged**
